name: Buner Deploy

on:
  push:
    branches:
      - release
    paths:
      - package.json

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Publish to NPM
        run: bun publish --access public
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.ORG_NPM_TOKEN }}
